# Generated by Django 3.2.10 on 2022-03-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
