# Generated by Django 3.2.10 on 2022-03-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifierApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='image_path',
        ),
        migrations.AddField(
            model_name='prediction',
            name='image',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
